export const dummyfiles = {
    nickname: "영블입니다",
    like_list: [
      {
        r_code:0,
        restaurant_name: "테스트 레스토랑",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:1,
        restaurant_name: "테스트 레스토랑2",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 중구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:2,
        restaurant_name: "테스트 레스토랑3",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 용산구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:3,
        restaurant_name: "테스트 레스토랑4",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 성동구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:4,
        restaurant_name: "테스트 레스토랑5",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 광진구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:5,
        restaurant_name: "테스트 레스토랑6",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 동대문구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:6,
        restaurant_name: "테스트 레스토랑7",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 중랑구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:7,
        restaurant_name: "테스트 레스토랑8",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 성북구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:8,
        restaurant_name: "테스트 레스토랑9",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 강북구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:9,
        restaurant_name: "테스트 레스토랑10",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 노원구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:10,
        restaurant_name: "테스트 레스토랑11",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 은평구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:11,
        restaurant_name: "테스트 레스토랑12",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 서대문구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:12,
        restaurant_name: "테스트 레스토랑13",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 마포구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:13,
        restaurant_name: "테스트 레스토랑14",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 양천구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:14,
        restaurant_name: "테스트 레스토랑15",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 강서구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:15,
        restaurant_name: "테스트 레스토랑16",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 구로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:16,
        restaurant_name: "테스트 레스토랑17",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 금천구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:17,
        restaurant_name: "테스트 레스토랑18",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 영등포구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:18,
        restaurant_name: "테스트 레스토랑19",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 동작구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:19,
        restaurant_name: "테스트 레스토랑20",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 관악구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:20,
        restaurant_name: "테스트 레스토랑21",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 서초구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:21,
        restaurant_name: "테스트 레스토랑22",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 강남구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:22,
        restaurant_name: "테스트 레스토랑23",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 송파구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:23,
        restaurant_name: "테스트 레스토랑24",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 강동구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:24,
        restaurant_name: "테스트 레스토랑25",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:25,
        restaurant_name: "테스트 레스토랑26",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:26,
        restaurant_name: "테스트 레스토랑27",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:27,
        restaurant_name: "테스트 레스토랑28",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
      {
        r_code:28,
        restaurant_name: "테스트 레스토랑29",
        img: "https://t1.daumcdn.net/cfile/tistory/2513B53E55DB206927",
        address: "서울특별시 종로구",
        star: 0,
        options: {
          takeout: true,
          parking: false,
          pet: false,
          nokids: false,
        },
      },
    ]
  }